// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAukxsNVCYLePX9CzA0tXbtnF7Dn5BNXlA',
    appId: '1:448439117336:web:4343dc69c22294b6d4456d',
    messagingSenderId: '448439117336',
    projectId: 'drowsydriver-eebba',
    authDomain: 'drowsydriver-eebba.firebaseapp.com',
    storageBucket: 'drowsydriver-eebba.firebasestorage.app',
    measurementId: 'G-HT96FG82K3',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp27Z3thWF5TpaL-Z2JiqaVHJ-zg9TJwA',
    appId: '1:448439117336:ios:3642925f678bb5e9d4456d',
    messagingSenderId: '448439117336',
    projectId: 'drowsydriver-eebba',
    storageBucket: 'drowsydriver-eebba.firebasestorage.app',
    iosClientId: '448439117336-khe0lngtcn8t30jffrb8mnj9f3mq0p85.apps.googleusercontent.com',
    iosBundleId: 'com.example.drowsyDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp27Z3thWF5TpaL-Z2JiqaVHJ-zg9TJwA',
    appId: '1:448439117336:ios:3642925f678bb5e9d4456d',
    messagingSenderId: '448439117336',
    projectId: 'drowsydriver-eebba',
    storageBucket: 'drowsydriver-eebba.firebasestorage.app',
    iosClientId: '448439117336-khe0lngtcn8t30jffrb8mnj9f3mq0p85.apps.googleusercontent.com',
    iosBundleId: 'com.example.drowsyDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAukxsNVCYLePX9CzA0tXbtnF7Dn5BNXlA',
    appId: '1:448439117336:web:76384a0cc2c67baed4456d',
    messagingSenderId: '448439117336',
    projectId: 'drowsydriver-eebba',
    authDomain: 'drowsydriver-eebba.firebaseapp.com',
    storageBucket: 'drowsydriver-eebba.firebasestorage.app',
    measurementId: 'G-6NLHVLSEY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCihnnm-erN92ioo68ASxAM22dkgSMsCrw',
    appId: '1:448439117336:android:543fe4057d9e6a0dd4456d',
    messagingSenderId: '448439117336',
    projectId: 'drowsydriver-eebba',
    storageBucket: 'drowsydriver-eebba.firebasestorage.app',
  );

}